### ISSUE TITLE
9.7.9 twod-array-tester.java Has An Issue

### ISSUE THREAD

**Issue by kw05** [31Carlton7/apcs-codehs#2]
There is an issue in the "TwoDArray.java" that causes the "Testing unequal integer arrays" test case on CodeHS to fail. The problem is that the code does NOT use the row/column length of the smaller 2D array, instead always just using the array from the private variable myArray- which causes an OutOfBounds Error when the other array is smaller. Here is a fixed version of the code for TwoDArray.java:

```
public class TwoDArray {

    private Object[][] myArray;
    
    public TwoDArray(Object[][] input)
    {
        myArray = input;
    }
    
    public boolean equals(Object[][] other)
    {
//fixed ↓
        int smallerRow = 0;
        if (myArray.length <= other.length)
            smallerRow = myArray.length;
        else 
            smallerRow = other.length;
        int smallerCol = 0;
        if (myArray[0].length <= other[0].length)
            smallerCol = myArray[0].length;
        else 
            smallerCol = other[0].length;
//fixed ↑
        for (int i = 0; i < smallerRow; i++)
        {
            for (int j = 0; j < smallerCol; j++)
            {
                if (!myArray[i][j].equals(other[i][j])) 
                {
                    return false;
                }
            }
        }
        return true;
    }
}
```

**Comment by Aeris-Fox** [comment]
( not sure if you knew this, but this is why pull requests exist :] )

**Comment by 31Carlton7** [comment]
> ( not sure if you knew this, but this is why pull requests exist :] )

I was just about to say this lol.

**Comment by 31Carlton7** [comment]
Just put some curly braces in there, and fix your indenting to fit with the rest of the file and submit a Pull Request and I'll accept it

**Comment by kw05** [comment]
Whoops, forgot about that lol. Just submitted one, thanks
